import { Character } from "./types";

export const MOCK_CHARACTERS: Character[] = [
  {
    id: "c1",
    name: "Garrick The Brave",
    level: 3,
    class: "Paladin",
    subclass: "Oath of Devotion",
    species: "Human",
    background: "Soldier",
    alignment: "Lawful Good",
    hp: { current: 28, max: 28, temp: 0 },
    ac: 18,
    init: 1,
    speed: 30,
    profBonus: 2,
    stats: { STR: 16, DEX: 10, CON: 14, INT: 10, WIS: 12, CHA: 15 },
    skills: ["Athletics", "Persuasion"],
    languages: ["Common"],
    feats: ["Savage Attacker"],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuD2QLD0dJ6wAOh2-H7nRgLrTanWwr_OY50vupYWkkdd6LQLQHOWc0Gi0mFVapUEU0p-EpMu3YYxluk_2gBDv6zr0Sugj6EglC4p7Hzeh2ePDmBaTTvkS9Ev91EXFBzXzlsKAd5rkDeQypcZpiSc11BE3sCl_2uXlsoBaGLI_G9a4M8ruqxX8qYuibAj9cACIs1wKJRjAoK5iHhLk3rkeR1zNkwjDwABSH72pV_uOs83RlKF2yCwWQbeecc9FX8AuMoCy8DdBa-9326S"
  },
  {
    id: "c2",
    name: "Elara Moonwhisper",
    level: 5,
    class: "Wizard",
    subclass: "Evocation",
    species: "Elf",
    background: "Sage",
    alignment: "Neutral Good",
    hp: { current: 22, max: 22, temp: 0 },
    ac: 12,
    init: 2,
    speed: 30,
    profBonus: 3,
    stats: { STR: 8, DEX: 14, CON: 12, INT: 18, WIS: 14, CHA: 10 },
    skills: ["Arcana", "History"],
    languages: ["Common", "Elvish", "Draconic"],
    feats: ["Magic Initiate (Wizard)"],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC83MqZyI9EfmkqwJ55ZdSV7wyMmdLf_r1RKBuN3dnT38HKEXE9xp4SxOF4nnWVKV1P-6pC93EnVbbbs-nkH5WXh16xC0sKwktsCdSEP7vcqWJaL-GbHaLt3SPaVPPs7eqhVCzuKNdcOGO3hcztn9ZmJreWRGvQK3BWcMXTMnHak04kEjkBKzNra2voSXlbpf_MZxtjPV3Ir8GRGH2JyfXEOIFQuDH0O8JMeDZn7c7nJgNRYSa-7B7tv5123BwaWuQBw38RaMM6onOj"
  },
  {
    id: "c3",
    name: "Throg",
    level: 1,
    class: "Barbarian",
    subclass: "Berserker",
    species: "Dwarf",
    background: "Outlander",
    alignment: "Chaotic Neutral",
    hp: { current: 15, max: 15, temp: 0 },
    ac: 14,
    init: 2,
    speed: 25,
    profBonus: 2,
    stats: { STR: 17, DEX: 14, CON: 16, INT: 8, WIS: 10, CHA: 8 },
    skills: ["Athletics", "Survival"],
    languages: ["Common", "Dwarvish"],
    feats: ["Tough"],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCgGhbiIXk5cP6Q_z92LCi-HnNNeh7clKWPBiOJLYZUz9m3fun1Nz8a5zIXEyoNTGtGKU58iHNU7Vb0rAJYt-bIDxMo_YULdp11w0xeHIF_cZFHw5rw02o27it8esb9puQ6axDedJZxEGG06UpWprgjZok9NPD7SsVEpiyOb05H0odeY4Qurti8gGM57g9Mr5onrb3O9s2upyz83WLfk3l3DooLLWuzk42zd6shXXLZ4u8rxLSTyDBFRaa41_rO-2TWcSAq4_p9wYMM"
  },
  {
    id: "c4",
    name: "Sylas the Shadow",
    level: 4,
    class: "Rogue",
    subclass: "Thief",
    species: "Halfling",
    background: "Criminal",
    alignment: "Chaotic Good",
    hp: { current: 24, max: 24, temp: 0 },
    ac: 16,
    init: 4,
    speed: 25,
    profBonus: 2,
    stats: { STR: 10, DEX: 18, CON: 12, INT: 13, WIS: 10, CHA: 14 },
    skills: ["Stealth", "Sleight of Hand", "Deception"],
    languages: ["Common", "Halfling"],
    feats: ["Alert"],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJaOk8hlb1Gat_iMmu5wYLJmB-sFTAqYnmaauH6b2UhCDQ6wRe825MuW2rmoItPGDKzXSoOOD8czydKrPhFJBUHw7BjZls6w1gpAUdVqCjE1SwOoKaRBkhBOC1MUQ0-b7WTrfyNAkggTw0gyhIMi3alY6PhUqgXsHEzoyY3vrVXLykFrx2nSn8svvyWbTGOOX4HcjRtJyFoSBQ24Yv40LS1JkfjcYYnXwsu3Ja8oT7CO0gwjA9YtCZz2dCHDM2h6AoTXhGkSYJYKwH"
  },
  {
    id: "c5",
    name: "Thorn",
    level: 5,
    class: "Fighter",
    subclass: "Champion",
    species: "Human",
    background: "Folk Hero",
    alignment: "Neutral Good",
    hp: { current: 42, max: 58, temp: 0 },
    ac: 18,
    init: 3,
    speed: 30,
    profBonus: 3,
    stats: { STR: 16, DEX: 14, CON: 16, INT: 8, WIS: 12, CHA: 10 },
    skills: ["Survival", "Animal Handling"],
    languages: ["Common"],
    feats: ["Great Weapon Master"],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA6jSCpdLMYhMuOQn5CWTc4HBJFAgMre9gobPmPpE5UgWvBWXY9_zpDU1aoucKc9-3pk4mY_JdZXB3ZrKPSBzK6xK5-k17mmFcEyi4hckKFWo8YNB1TSKkTJLrzrsuhnMHja_K0eIS6y4Znpq3ATGkYauK5yZwAZbuBgpavnxG-bZChxn8d-2FW3q40QcPfjB5n9cr0L8_CLmEuR63SShskojm5Gd4o0SOjUOef0SmTErXYaKVCAGvdyyTv5ViQbz58FomAk6rFUUX1"
  }
];

export const MAP_TEXTURE = "https://lh3.googleusercontent.com/aida-public/AB6AXuCci_9LlzLBRVKMl1mc_U-PI7pOA37e5v9j0IBVPIWRTYMaSEvDrM1dNax_MOPK-cvdJKWHInGTW3RUm3dfYRMTZ5897zlqHPcb4EgyRbBn918kFop8Q7PDDdLrBSMF1NifHl7bvNMqa0jmiqxcY36X3xpBWnBZYFL42kFa8rqcCl9HKLdzHTFmAStCV2e9bZm1NjB_czY2xLfbStx3TdJheuPvI3tPOG8DwFefJ1fFM3ocgOa04FuaZHvYn0RBqQHqDyx1Tt2TSSf8";

// Map raw data names to UI elements (Colors, Icons, Roles)
export const CLASS_UI_MAP: Record<string, { role: string, color: string, icon: string }> = {
  "Barbarian": { role: "Tanque de Furia", color: "text-orange-600", icon: "swords" },
  "Bard": { role: "Apoyo y Control", color: "text-purple-500", icon: "music_note" },
  "Cleric": { role: "Curación Divina", color: "text-yellow-500", icon: "verified_user" },
  "Druid": { role: "Naturaleza y Formas", color: "text-green-600", icon: "forest" },
  "Fighter": { role: "Maestro de Armas", color: "text-red-500", icon: "sports_martial_arts" },
  "Monk": { role: "Artes Marciales", color: "text-blue-400", icon: "self_improvement" },
  "Paladin": { role: "Guerrero Santo", color: "text-yellow-600", icon: "shield" },
  "Ranger": { role: "Explorador", color: "text-emerald-500", icon: "radar" },
  "Rogue": { role: "Sigilo y Daño", color: "text-slate-400", icon: "visibility_off" },
  "Sorcerer": { role: "Magia Innata", color: "text-red-400", icon: "local_fire_department" },
  "Warlock": { role: "Pacto Arcano", color: "text-purple-700", icon: "skull" },
  "Wizard": { role: "Maestro Arcano", color: "text-blue-600", icon: "auto_fix_high" },
};

export const SPECIES_UI_MAP: Record<string, { color: string, icon: string }> = {
  "Human": { color: "text-blue-500", icon: "accessibility_new" },
  "Elf": { color: "text-green-500", icon: "eco" },
  "Dwarf": { color: "text-orange-600", icon: "construction" },
  "Halfling": { color: "text-yellow-500", icon: "directions_walk" },
  "Dragonborn": { color: "text-red-600", icon: "local_fire_department" },
  "Gnome": { color: "text-purple-500", icon: "psychology" },
  "Orc": { color: "text-emerald-700", icon: "fitness_center" },
  "Tiefling": { color: "text-rose-500", icon: "contrast" },
  "Aasimar": { color: "text-amber-400", icon: "flare" },
  "Goliath": { color: "text-slate-500", icon: "landscape" },
};